CREATE TABLE "memento_activity" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "memento_activity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"publicId" text NOT NULL,
	"sourceType" text NOT NULL,
	"createdByUserId" integer,
	"title" text NOT NULL,
	"description" text,
	"latitude" double precision NOT NULL,
	"longitude" double precision NOT NULL,
	"radiusMeters" integer,
	"days" text NOT NULL,
	"specificDates" date[],
	"timeOfDay" text,
	"startTime" time,
	"endTime" time,
	"category" text NOT NULL,
	"minDurationMinutes" integer,
	"maxDurationMinutes" integer,
	"isIndoor" boolean,
	"costLevel" smallint,
	"tags" text[] DEFAULT '{}'::text[] NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"priority" smallint DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "activity_source_type_enum" CHECK ("memento_activity"."sourceType" in ('curated','user')),
	CONSTRAINT "activity_days_enum" CHECK ("memento_activity"."days" in ('weekday','weekend','any')),
	CONSTRAINT "activity_category_enum" CHECK ("memento_activity"."category" in ('food','nature','entertainment','social')),
	CONSTRAINT "activity_time_of_day_enum" CHECK ("memento_activity"."timeOfDay" is null or "memento_activity"."timeOfDay" in ('early-morning','morning','late-morning','afternoon','evening','night','late-night')),
	CONSTRAINT "activity_cost_level_range" CHECK ("memento_activity"."costLevel" is null or ("memento_activity"."costLevel" >= 0 and "memento_activity"."costLevel" <= 3)),
	CONSTRAINT "activity_time_range_order" CHECK ("memento_activity"."startTime" is null or "memento_activity"."endTime" is null or "memento_activity"."startTime" <= "memento_activity"."endTime"),
	CONSTRAINT "activity_source_type_owner_guard" CHECK (("memento_activity"."sourceType" = 'curated' and "memento_activity"."createdByUserId" is null) or ("memento_activity"."sourceType" = 'user' and "memento_activity"."createdByUserId" is not null))
);
--> statement-breakpoint
CREATE TABLE "memento_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "memento_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "memento_recommendation_note" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "memento_recommendation_note_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"publicId" text NOT NULL,
	"userId" integer NOT NULL,
	"activityId" integer NOT NULL,
	"slotStartAt" timestamp with time zone NOT NULL,
	"slotEndAt" timestamp with time zone NOT NULL,
	"note" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "recommendation_note_slot_order" CHECK ("memento_recommendation_note"."slotStartAt" <= "memento_recommendation_note"."slotEndAt")
);
--> statement-breakpoint
CREATE TABLE "memento_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "memento_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"publicId" text NOT NULL,
	"clerkUserId" text NOT NULL,
	"timezone" text DEFAULT 'America/New_York' NOT NULL,
	"email" text,
	"name" text,
	"imageUrl" text,
	"calendarConnected" boolean DEFAULT false NOT NULL,
	"calendarConnectionStatus" text,
	"calendarScopes" text[],
	"calendarLastSyncAt" timestamp with time zone,
	"calendarSyncError" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "user_calendar_connection_status_enum" CHECK ("memento_user"."calendarConnectionStatus" is null or "memento_user"."calendarConnectionStatus" in ('connected','expired','revoked','error'))
);
--> statement-breakpoint
ALTER TABLE "memento_activity" ADD CONSTRAINT "memento_activity_createdByUserId_memento_user_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "public"."memento_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "memento_recommendation_note" ADD CONSTRAINT "memento_recommendation_note_userId_memento_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."memento_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "memento_recommendation_note" ADD CONSTRAINT "memento_recommendation_note_activityId_memento_activity_id_fk" FOREIGN KEY ("activityId") REFERENCES "public"."memento_activity"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "activity_public_id_idx" ON "memento_activity" USING btree ("publicId");--> statement-breakpoint
CREATE INDEX "activity_source_type_idx" ON "memento_activity" USING btree ("sourceType");--> statement-breakpoint
CREATE INDEX "activity_created_by_user_id_idx" ON "memento_activity" USING btree ("createdByUserId");--> statement-breakpoint
CREATE INDEX "activity_category_idx" ON "memento_activity" USING btree ("category");--> statement-breakpoint
CREATE INDEX "activity_location_idx" ON "memento_activity" USING btree ("latitude","longitude");--> statement-breakpoint
CREATE INDEX "name_idx" ON "memento_post" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "recommendation_note_public_id_idx" ON "memento_recommendation_note" USING btree ("publicId");--> statement-breakpoint
CREATE INDEX "recommendation_note_user_id_idx" ON "memento_recommendation_note" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "recommendation_note_activity_id_idx" ON "memento_recommendation_note" USING btree ("activityId");--> statement-breakpoint
CREATE INDEX "recommendation_note_slot_start_idx" ON "memento_recommendation_note" USING btree ("slotStartAt");--> statement-breakpoint
CREATE UNIQUE INDEX "user_public_id_idx" ON "memento_user" USING btree ("publicId");--> statement-breakpoint
CREATE UNIQUE INDEX "user_clerk_user_id_idx" ON "memento_user" USING btree ("clerkUserId");--> statement-breakpoint
CREATE INDEX "user_calendar_connected_idx" ON "memento_user" USING btree ("calendarConnected");