import { generateId } from "@/lib/id";
import { db } from "@/server/db";
import { activities } from "@/server/db/schema";

async function main() {
	// Suggestions-only seed data (from suggestions.md).
	// Keep coordinates/radii aligned to the prompt bank so the demo feels real.
	const demoActivities: Array<typeof activities.$inferInsert> = [
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Arts Quad: capture the light (quick photo)",
			description:
				"The light is different right now than it'll be in an hour. Take a photo of exactly what it looks like this second.",
			latitude: 42.4491,
			longitude: -76.4842,
			radiusMeters: 150,
			days: "any",
			timeOfDay: "evening",
			category: "nature",
			minDurationMinutes: 5,
			maxDurationMinutes: null,
			priority: 12,
			isActive: true,
			tags: ["photo", "prompt", "scenery", "campus"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Olin/Uris: document your study spot",
			description:
				"Your study spot right now. Messy? Organized? Honest photo + a one-sentence caption.",
			latitude: 42.4478,
			longitude: -76.484,
			radiusMeters: 100,
			days: "any",
			timeOfDay: "late-morning",
			category: "entertainment",
			minDurationMinutes: 5,
			maxDurationMinutes: null,
			priority: 11,
			isActive: true,
			tags: ["study", "prompt", "photo", "library"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Ho Plaza: capture the energy (1 photo)",
			description:
				"What's happening right now—tabling, chalk, people passing through? Capture the moment like a tiny time capsule.",
			latitude: 42.4468,
			longitude: -76.4854,
			radiusMeters: 100,
			days: "weekday",
			timeOfDay: "afternoon",
			category: "social",
			minDurationMinutes: 5,
			maxDurationMinutes: null,
			priority: 10,
			isActive: true,
			tags: ["photo", "prompt", "candid", "campus"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Libe Slope: lie down + sky shot",
			description:
				"Lie down for 10 seconds. Point the camera straight up. That's today's sky and it won't come back.",
			latitude: 42.448,
			longitude: -76.487,
			radiusMeters: 120,
			days: "any",
			timeOfDay: "afternoon",
			category: "nature",
			minDurationMinutes: 5,
			maxDurationMinutes: null,
			priority: 10,
			isActive: true,
			tags: ["photo", "prompt", "creative", "campus"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "McGraw Tower: caption the chimes",
			description:
				"The chimes just played. Snap a photo of the tower and caption it with the song (or your best guess).",
			latitude: 42.4478,
			longitude: -76.4846,
			radiusMeters: 80,
			days: "any",
			timeOfDay: "afternoon",
			category: "entertainment",
			minDurationMinutes: 5,
			maxDurationMinutes: null,
			priority: 10,
			isActive: true,
			tags: ["photo", "prompt", "tower", "campus"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Gates Hall: late-night grind shot",
			description:
				"Late night in Gates. Screens glowing. Capture the grind energy (even if it's just your setup).",
			latitude: 42.445,
			longitude: -76.4808,
			radiusMeters: 120,
			days: "any",
			timeOfDay: "night",
			category: "entertainment",
			minDurationMinutes: 5,
			maxDurationMinutes: null,
			priority: 9,
			isActive: true,
			tags: ["study", "prompt", "night"],
		},
		// MORNING (fits 9:00–10:45)
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Collegetown coffee + people watch",
			description:
				"Grab coffee and just observe the morning flow for 20 minutes.",
			latitude: 42.4429,
			longitude: -76.4857,
			radiusMeters: 200,
			days: "any",
			timeOfDay: "morning",
			category: "social",
			minDurationMinutes: 15,
			maxDurationMinutes: 45,
			priority: 10,
			isActive: true,
			tags: ["coffee", "chill"],
		},

		// MIDDAY (fits 12:15–1:45)
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Quick lunch walk loop",
			description: "Walk a loop around campus while eating something quick.",
			latitude: 42.447,
			longitude: -76.484,
			radiusMeters: 300,
			days: "any",
			timeOfDay: "late-morning",
			category: "nature",
			minDurationMinutes: 20,
			maxDurationMinutes: 60,
			priority: 11,
			isActive: true,
			tags: ["walk", "food"],
		},

		// AFTERNOON (fits 3:15–4:45)
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Libe Slope reset break",
			description: "Sit, lie down, or just pause for a proper reset.",
			latitude: 42.448,
			longitude: -76.487,
			radiusMeters: 120,
			days: "any",
			timeOfDay: "afternoon",
			category: "nature",
			minDurationMinutes: 15,
			maxDurationMinutes: 60,
			priority: 12,
			isActive: true,
			tags: ["break", "mental"],
		},

		// EVENING (fits 6:15–9:00)
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Sunset walk + reflection",
			description: "Walk and record a quick voice note about your day.",
			latitude: 42.4495,
			longitude: -76.486,
			radiusMeters: 300,
			days: "any",
			timeOfDay: "evening",
			category: "nature",
			minDurationMinutes: 20,
			maxDurationMinutes: 90,
			priority: 13,
			isActive: true,
			tags: ["sunset", "reflect"],
		},

		// LONG SLOT FILLER (important for 165 min gap)
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Deep work session (change location)",
			description: "Pick a new spot and focus for a full session.",
			latitude: 42.445,
			longitude: -76.4808,
			radiusMeters: 200,
			days: "any",
			timeOfDay: "evening",
			category: "entertainment",
			minDurationMinutes: 60,
			maxDurationMinutes: 180,
			priority: 14,
			isActive: true,
			tags: ["focus", "study"],
		},
		// WEEKEND-FIRST ACTIVITIES (tuned to reliably match Saturday free slots)
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Saturday farmers market browse",
			description:
				"Walk the stalls, pick one snack, and people-watch for a bit.",
			latitude: 42.4406,
			longitude: -76.4966,
			radiusMeters: 450,
			days: "weekend",
			timeOfDay: "morning",
			category: "food",
			minDurationMinutes: 15,
			maxDurationMinutes: null,
			priority: 18,
			isActive: true,
			tags: ["market", "weekend", "food"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Cascadilla Gorge overlook pause",
			description:
				"Take a short walk to the overlook and stay there long enough to fully reset.",
			latitude: 42.4439,
			longitude: -76.4924,
			radiusMeters: 300,
			days: "weekend",
			timeOfDay: "late-morning",
			category: "nature",
			minDurationMinutes: 10,
			maxDurationMinutes: null,
			priority: 17,
			isActive: true,
			tags: ["gorge", "walk", "weekend"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Commons lunch window mission",
			description:
				"Grab something you have never tried before and eat it outside if weather allows.",
			latitude: 42.4396,
			longitude: -76.4969,
			radiusMeters: 500,
			days: "weekend",
			timeOfDay: "afternoon",
			category: "food",
			minDurationMinutes: 20,
			maxDurationMinutes: null,
			priority: 19,
			isActive: true,
			tags: ["lunch", "commons", "weekend"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Stewart Park waterfront loop",
			description:
				"Do a relaxed out-and-back by the water and take one photo at the farthest point.",
			latitude: 42.4634,
			longitude: -76.5125,
			radiusMeters: 700,
			days: "weekend",
			timeOfDay: "afternoon",
			category: "nature",
			minDurationMinutes: 25,
			maxDurationMinutes: null,
			priority: 16,
			isActive: true,
			tags: ["water", "walk", "photo"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Saturday social call sprint",
			description:
				"Call or voice note one friend you have not checked in with this week.",
			latitude: 42.4468,
			longitude: -76.4852,
			days: "weekend",
			category: "social",
			minDurationMinutes: 5,
			maxDurationMinutes: null,
			priority: 20,
			isActive: true,
			tags: ["social", "quick", "weekend"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Cornell Botanic Gardens slow walk",
			description:
				"Pick one trail segment and walk it without headphones for a full reset.",
			latitude: 42.4493,
			longitude: -76.4719,
			radiusMeters: 900,
			days: "weekend",
			timeOfDay: "afternoon",
			category: "nature",
			minDurationMinutes: 20,
			maxDurationMinutes: null,
			priority: 15,
			isActive: true,
			tags: ["garden", "reset", "weekend"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Cook House snack and journal",
			description:
				"Get a small snack and write three lines about your week so far.",
			latitude: 42.4535,
			longitude: -76.4789,
			days: "weekend",
			timeOfDay: "late-morning",
			category: "food",
			minDurationMinutes: 10,
			maxDurationMinutes: null,
			priority: 14,
			isActive: true,
			tags: ["snack", "journal", "weekend"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "State Theatre matinee plan",
			description:
				"Check what is showing and decide on a movie, even if you go later.",
			latitude: 42.4399,
			longitude: -76.496,
			radiusMeters: 400,
			days: "weekend",
			timeOfDay: "afternoon",
			category: "entertainment",
			minDurationMinutes: 10,
			maxDurationMinutes: null,
			priority: 13,
			isActive: true,
			tags: ["movie", "plan", "weekend"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Sunset at Libe Slope with no phone",
			description:
				"Sit for ten quiet minutes before taking one final sunset shot.",
			latitude: 42.448,
			longitude: -76.487,
			radiusMeters: 250,
			days: "weekend",
			timeOfDay: "evening",
			category: "nature",
			minDurationMinutes: 10,
			maxDurationMinutes: null,
			priority: 21,
			isActive: true,
			tags: ["sunset", "quiet", "weekend"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Board game hour at home base",
			description:
				"Host a quick board game or card session with whoever is around.",
			latitude: 42.4467,
			longitude: -76.4828,
			days: "weekend",
			timeOfDay: "evening",
			category: "social",
			minDurationMinutes: 30,
			maxDurationMinutes: null,
			priority: 17,
			isActive: true,
			tags: ["games", "friends", "weekend"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Night dessert walk in Collegetown",
			description: "Take a short walk to grab dessert and rate it out of ten.",
			latitude: 42.4427,
			longitude: -76.4859,
			radiusMeters: 350,
			days: "weekend",
			timeOfDay: "night",
			category: "food",
			minDurationMinutes: 15,
			maxDurationMinutes: null,
			priority: 18,
			isActive: true,
			tags: ["dessert", "walk", "night"],
		},
		{
			publicId: generateId("act"),
			sourceType: "curated",
			createdByUserId: null,
			title: "Weekend long free-slot project block",
			description:
				"Pick one personal project and make clear progress in a single uninterrupted block.",
			latitude: 42.4451,
			longitude: -76.4809,
			days: "weekend",
			category: "entertainment",
			minDurationMinutes: 45,
			maxDurationMinutes: null,
			priority: 22,
			isActive: true,
			tags: ["project", "focus", "long-slot"],
		},
	];

	// Avoid duplicate inserts on rerun by title+sourceType.
	const existing = await db.query.activities.findMany({
		where: (a, { eq }) => eq(a.sourceType, "curated"),
		columns: { title: true },
	});
	const existingTitles = new Set(existing.map((e) => e.title));
	const toInsert = demoActivities.filter((a) => !existingTitles.has(a.title));

	if (toInsert.length === 0) {
		console.log("Seed: no new activities to insert.");
		process.exit(0);
	}

	await db.insert(activities).values(toInsert);
	console.log(`Seed: inserted ${toInsert.length} activities.`);
	process.exit(0);
}

await main().catch((err) => {
	console.error(err);
	process.exit(1);
});
